DPC 971 Feature: Add Snyk scans for Github Actions
CMSgov/dpc-app pull request #1150
Opened 2020-12-19 17:55 UTC by lostpurplecow

Signed-off-by: Jeff Corpuz <jcorpuz@fearless.tech>

### Fixes [DPC-xxx](https://jira.cms.gov/browse/DPC-xxx)

### Proposed Changes

### Change Details

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] no PHI/PII is affected by this change

### Acceptance Validation

### Feedback Requested

2020-12-19 19:32 UTC, msnook requested changes
I'm curious why there are Snyk blocking failures in this feature branch, but the scans occurring from `master` (via Jenkins) are clean.  At the moment, this PR is blocked because of the vulnerabilities detected via Snyk.  Are there configuration differences between the Snyk integration in Actions vs the Snyk integration in Jenkins?

2020-12-19 19:43 UTC, lostpurplecow commented
> I'm curious why there are Snyk blocking failures in this feature branch, but the scans occurring from `master` (via Jenkins) are clean. At the moment, this PR is blocked because of the vulnerabilities detected via Snyk. Are there configuration differences between the Snyk integration in Actions vs the Snyk integration in Jenkins?

The configuration for this GA is the same as the one in Jenkins as you can see here:
```groovy    
stage('Snyk Test') {
      steps {
        dir('dpc-app') {
          snykSecurity failOnIssues: !params.SNYK_OVERRIDE, severity: 'high', snykInstallation: 'dpc-snyk', snykTokenId: 'SNYK_API_TOKEN'
        }
      }
    }
```

2020-12-19 20:11 UTC, msnook commented
> > I'm curious why there are Snyk blocking failures in this feature branch, but the scans occurring from `master` (via Jenkins) are clean. At the moment, this PR is blocked because of the vulnerabilities detected via Snyk. Are there configuration differences between the Snyk integration in Actions vs the Snyk integration in Jenkins?
> 
> The configuration for this GA is the same as the one in Jenkins as you can see here:
> 
> ```groovy
> stage('Snyk Test') {
>       steps {
>         dir('dpc-app') {
>           snykSecurity failOnIssues: !params.SNYK_OVERRIDE, severity: 'high', snykInstallation: 'dpc-snyk', snykTokenId: 'SNYK_API_TOKEN'
>         }
>       }
>     }
> ```
> 
> Hmm though judging from this snapshot of last successful build there were no issues:
> https://app.snyk.io/org/oeda/project/70afbed4-f7f9-45ae-8309-f70a09ed2541/history/7a5093ef-c3b9-4f15-a1b6-71ac9ec5bc8a
> 
> Actually, w/ GA we'd have to add the file paths for targetting dependencies... w/ Jenkins it is only going for root... therefore it may seem we have discovered a configuration issue o.O

Cool, is the configuration issue in Jenkins (meaning that there are vulnerabilities we need to fix now)?  Might we need to use `targetFile` in the Jenkins config, similar to how we're using `--file` in the GA config?

2020-12-19 21:52 UTC, lostpurplecow commented
> > > I'm curious why there are Snyk blocking failures in this feature branch, but the scans occurring from `master` (via Jenkins) are clean. At the moment, this PR is blocked because of the vulnerabilities detected via Snyk. Are there configuration differences between the Snyk integration in Actions vs the Snyk integration in Jenkins?
> > 
> > 
> > The configuration for this GA is the same as the one in Jenkins as you can see here:
> > ```groovy
> > stage('Snyk Test') {
> >       steps {
> >         dir('dpc-app') {
> >           snykSecurity failOnIssues: !params.SNYK_OVERRIDE, severity: 'high', snykInstallation: 'dpc-snyk', snykTokenId: 'SNYK_API_TOKEN'
> >         }
> >       }
> >     }
> > ```
> > 
> > 
> > Hmm though judging from this snapshot of last successful build there were no issues:
> > https://app.snyk.io/org/oeda/project/70afbed4-f7f9-45ae-8309-f70a09ed2541/history/7a5093ef-c3b9-4f15-a1b6-71ac9ec5bc8a
> > Actually, w/ GA we'd have to add the file paths for targetting dependencies... w/ Jenkins it is only going for root... therefore it may seem we have discovered a configuration issue o.O
> 
> Cool, is the configuration issue in Jenkins (meaning that there are vulnerabilities we need to fix now)? Might we need to use `targetFile` in the Jenkins config, similar to how we're using `--file` in the GA config?

Yes, that means there are vulnerabilities we'd need to fix now... 
Addressing here: https://github.com/CMSgov/dpc-ops/pull/282

2020-12-21 17:05 UTC, dhgreene commented on .github/workflows/ci-workflow.yml
> +          args: --severity-threshold=high --file=pom.xml
Should we include the other sources here, or perhaps use the directory-driven approach from the ops PR?

2020-12-23 17:07 UTC, orenfromberg approved these changes
tentatively approving, don't merge yet.

2020-12-23 17:11 UTC, orenfromberg commented
:taco:

2020-12-23 17:46 UTC, merged