DRAFT DPC-1146
CMSgov/dpc-app pull request #1242
Opened 2021-03-19 12:49 UTC by Sun-Mountain

### Fixes [DPC-xxx](https://jira.cms.gov/browse/DPC-xxx)

### Proposed Changes

### Change Details

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] no PHI/PII is affected by this change

### Acceptance Validation

### Feedback Requested

2021-03-26 19:19 UTC, msnook commented on .github/workflows/ci-workflow.yml
> +      - name: "Portals Build"
Nit - maybe `Web Portals Build`?

2021-03-26 19:20 UTC, msnook commented on Makefile
> +#Depicated TODO remove once make ci-portals is completely working.
This could be removed as part of this PR, right?

2021-03-26 19:21 UTC, msnook commented on Makefile
> +.PHONY: start-dpc
Is this target just for local development convenience?  It is not needed in the CI, right?  (Since the CI is separated between `api` and `portals`)

2021-03-26 19:22 UTC, msnook commented on docker-compose.all.yml
> +      - SIDEKIQ_ALIVE_PORT=4242
Why doesn't `web-sidekiq` need this env var set?

2021-03-26 19:27 UTC, msnook commented on docker-compose.all.yml
> +version: '3'
Why is the `docker-compose.all.yml` file needed?  There is lot of redundancy that already exists in `docker-compose.yml`.  Can't we just use the `docker-compose.yml` as the "base" and chain together the files to build the stack?
For example, something like:
```
docker-compose -f docker-compose.yml -f docker-compose-portals.yml up
```

2021-03-26 19:29 UTC, msnook commented on dpc-admin/docker/entrypoint.sh
> +    bundle exec rails server -b 0.0.0.0 -p 3000
@orenfromberg Does this align with your expectation?

2021-03-26 20:04 UTC, orenfromberg commented on dpc-admin/docker/entrypoint.sh
> +    bundle exec rails server -b 0.0.0.0 -p 3000
yeah, we specify the port for the admin service here: https://github.com/CMSgov/dpc-ops/blob/oren/DPC-1073-web-admin/terraform/modules/tiers/frontend/main.tf#L12

2021-03-29 15:41 UTC, SalGutierrez commented on Makefile
> +.PHONY: start-dpc
Correct

2021-03-29 16:33 UTC, SalGutierrez commented on .github/workflows/ci-workflow.yml
> +      - name: "Portals Build"
Fixed.

2021-03-29 16:33 UTC, SalGutierrez commented on Makefile
> +#Depicated TODO remove once make ci-portals is completely working.
Done.

2021-03-29 16:34 UTC, SalGutierrez commented on docker-compose.all.yml
> +      - SIDEKIQ_ALIVE_PORT=4242
Fixed, the port does not need to be specified.

2021-03-29 16:34 UTC, SalGutierrez commented on docker-compose.all.yml
> +version: '3'
done

2021-03-29 19:43 UTC, msnook commented on dpc-web/docker-compose.yml
> +#Depicated TODO remove once make ci-portals is completely working.
Can this be removed now?

2021-03-29 19:59 UTC, SalGutierrez commented on dpc-web/docker-compose.yml
> +#Depicated TODO remove once make ci-portals is completely working.
🤦 Missed it. Removed.

2021-03-29 20:11 UTC, msnook requested changes
I think this all looks great; however, we'll need to hold off on merging this until DPC-1201 is ready to be merged (otherwise, we'll break the pipeline [here](https://github.com/CMSgov/dpc-ops/blob/master/jenkins_files/Jenkinsfile.docker_build#L136)).

2021-04-01 18:26 UTC, msnook approved these changes
LGTM.  This will need to be merged at the same time as https://github.com/CMSgov/dpc-ops/pull/332

2021-04-05 14:11 UTC, orenfromberg reviewed
Looking good. I have a few questions for now to help me get some context around the changes.

2021-04-05 14:11 UTC, orenfromberg commented on dpc-admin/Rakefile
> +# Replace yarn with npm
what prompted this move from yarn to npm?

2021-04-05 15:38 UTC, Sun-Mountain commented on dpc-admin/Rakefile
> +# Replace yarn with npm
We've always used `npm`, but Rails 6 (which is what the admin app)  defaults to using yarn. To keep the web app and the admin app as similar as possible, we want to continue to use npm.

2021-04-05 18:43 UTC, Sun-Mountain commented on dpc-admin/README.md
> +DPC Admin: localhost:3000\
Oops, my mistake!

2021-04-05 18:46 UTC, Sun-Mountain commented on docker-compose.yml
> +      - POSTGRES_MULTIPLE_DATABASES=dpc_attribution,dpc_queue,dpc_auth,dpc_consent,dpc-website_development
Differently how?

2021-04-05 18:46 UTC, Sun-Mountain commented on docker-compose.yml
>      image: postgres
@SalGutierrez ?

2021-04-05 18:56 UTC, orenfromberg commented on docker-compose.yml
> +      - POSTGRES_MULTIPLE_DATABASES=dpc_attribution,dpc_queue,dpc_auth,dpc_consent,dpc-website_development
@Sun-Mountain I would have expected the database name to be something like `dpc_website` instead of `dpc-website_development`.

2021-04-05 19:11 UTC, orenfromberg commented on dpc-admin/README.md
> +DPC Admin: localhost:3000\
TIL x 2!

2021-04-05 19:16 UTC, Sun-Mountain commented on docker-compose.yml
> +      - POSTGRES_MULTIPLE_DATABASES=dpc_attribution,dpc_queue,dpc_auth,dpc_consent,dpc-website_development
@SalGutierrez would it be breaking if we rename the database?

2021-04-08 04:44 UTC, SalGutierrez commented on docker-compose.yml
> +      - POSTGRES_MULTIPLE_DATABASES=dpc_attribution,dpc_queue,dpc_auth,dpc_consent,dpc-website_development
not sure, thats what dpc-web has been using and what dpc-admin uses too during local dev

2021-04-08 04:45 UTC, SalGutierrez commented on docker-compose.yml
>      image: postgres
what is the version we are running @orenfromberg ?

2021-04-08 05:02 UTC, SalGutierrez commented on docker-compose.yml
> +      - POSTGRES_MULTIPLE_DATABASES=dpc_attribution,dpc_queue,dpc_auth,dpc_consent,dpc-website_development
looks like a rails thing, when rails creates the database it appends the environment if it is not prod.

2021-04-08 16:11 UTC, msnook commented on docker-compose.yml
>      image: postgres
@SalGutierrez @orenfromberg 
We are running `11.10`.  I think we should definitely pin, but I don't think we should do it as part of this PR.  I think its a tech debt item that is out-of-scope for Sal's work.  If you are OK with it, I'll add a tech debt item to SRE backlog to get this done for ACO API and DPC.  I fear that pinning as part of this PR will cause some unplanned breakages, and it should be handled separately.

2021-04-08 16:13 UTC, msnook commented
Once this PR is merged (or maybe even before, depending on how Github blocks in CI), we'll need to remove the below workflow item as a required step (since it was renamed):

<img width="753" alt="Screen Shot 2021-04-08 at 12 12 23 PM" src="https://user-images.githubusercontent.com/37818548/114060840-c937e580-9863-11eb-9cc4-02a83b609984.png">

2021-04-08 16:13 UTC, msnook approved these changes

2021-04-08 17:00 UTC, orenfromberg approved these changes
:shipit:

2021-04-08 20:44 UTC, merged