DPC-1313 check if file passed in request is valid and download if it is
CMSgov/dpc-app pull request #1292
Opened 2021-05-09 19:20 UTC by MrBilnon

### Fixes [DPC-1313](https://jira.cms.gov/browse/DPC-1313)

The ability to download export generated files

### Proposed Changes

- create a endpoint in attribution to check if file name passed in is valid (found in job where all job batches are done and in the same org as the auth token)
- if passes validation, grab and return the file in api

### Change Details

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [x] no PHI/PII is affected by this change

### Acceptance Validation

<img width="1376" alt="Screen Shot 2021-05-19 at 11 19 08 PM" src="https://user-images.githubusercontent.com/52384927/118918638-ad127400-b8f8-11eb-8bc8-773372f256d1.png">
<img width="1357" alt="Screen Shot 2021-05-19 at 11 20 01 PM" src="https://user-images.githubusercontent.com/52384927/118918703-c4516180-b8f8-11eb-9919-074d5e6712d9.png">

### Feedback Requested

2021-05-13 13:05 UTC, MrMorie approved these changes
LGTM

2021-05-13 14:56 UTC, dhgreene reviewed
The code looks good.  Would you be willing to add more to the acceptance section--screenshot of a file being downloaded, for instance?

2021-05-26 17:45 UTC, jonfulk requested changes
Looks good overall; only blocking because of the deleted check on `err` that I commented on. I am concerned that this will let a bug slip through as I was seeing during testing.

2021-05-26 17:45 UTC, jonfulk commented on dpc-go/dpc-attribution/src/service/service.go
> +	Export(writer http.ResponseWriter, request *http.Request)
i just changed these params to `w` and `r` to be consistent with the other routes in my last merge

2021-05-26 17:45 UTC, jonfulk commented on dpc-go/dpc-attribution/src/service/v1/data.go
> +	fileName, ok := r.Context().Value(middleware.ContextKeyFileName).(string)
you could reduce some lines of code here using the shared `FetchValueFromContext` helper method I added

2021-05-26 17:45 UTC, jonfulk commented on dpc-go/dpc-attribution/src/service/v1/job.go
>  		log.Error("Failed to retrieve NPIs for Group", zap.Error(err))
❌  i added this check for `err == nil` here because (unless the conditions are broken up) `err` could be nil, yet the other conditions could be true, resulting in no error message. I also saw code continuing to process in another case where `err` was nil but the other check was true where I expected `boom` to raise the error and not continue trying to process.

2021-05-26 17:45 UTC, jonfulk commented on dpc-go/dpc-attribution/src/repository/job_repository_v1.go
> +func (jr *JobRepositoryV1) IsFileValid(ctx context.Context, orgID string, fileName string) (*v1.FileInfo, error) {
could some of this be extracted to a couple private methods?

2021-05-26 18:05 UTC, jonfulk commented on dpc-go/dpc-attribution/src/go.sum
> +github.com/bxcodec/faker v2.0.1+incompatible/go.mod h1:BNzfpVdTwnFJ6GtfYTcQu6l6rHShT+veBxNCnjCx5XM=
we need to use `github.com/bxcodec/faker/v3`. You have to import it with the `/v3` on the end, otherwise it will automatically install v2 as well

2021-05-26 18:07 UTC, jonfulk commented on dpc-go/dpc-attribution/src/model/v1/patient.go
> +type Patient struct {
are you using this struct? I removed it in my last PR because even though I created it, I wasn't using it.

2021-05-26 18:14 UTC, MrMorie commented on dpc-go/dpc-attribution/src/repository/job_repository_v1.go
> +	sb.From("job_queue_batch_file f")
clever

2021-05-26 18:23 UTC, MrMorie commented on dpc-go/dpc-attribution/src/repository/job_repository_v1.go
> +			return nil, errors.New("Not all job batches are completed")
Not really a change request.
if we're not using statuses anywhere else, could we check for status==2 in the previous loop? and not need to maintain a list?

2021-05-26 20:09 UTC, MrBilnon commented on dpc-go/dpc-attribution/src/go.sum
> +github.com/bxcodec/faker v2.0.1+incompatible/go.mod h1:BNzfpVdTwnFJ6GtfYTcQu6l6rHShT+veBxNCnjCx5XM=
every place imports v3

2021-05-26 20:16 UTC, MrBilnon commented on dpc-go/dpc-attribution/src/service/v1/job.go
>  		log.Error("Failed to retrieve NPIs for Group", zap.Error(err))
just a merge issue, I'll correct it

2021-05-26 20:23 UTC, MrBilnon commented on dpc-go/dpc-attribution/src/repository/job_repository_v1.go
> +			return nil, errors.New("Not all job batches are completed")
okay, got rid of list

2021-05-26 20:48 UTC, jonfulk approved these changes
LGTM

2021-05-27 06:07 UTC, MrMorie approved these changes
LGTM 🛸

2021-05-27 16:34 UTC, MrBilnon commented on dpc-go/dpc-attribution/src/model/v1/patient.go
> +type Patient struct {
nope, these are the merge problems I face

2021-05-27 16:46 UTC, MrMorie approved these changes
LGTM

2021-05-27 17:15 UTC, merged