DPC-1438 Add Mutual TLS to GO DPC-API
CMSgov/dpc-app pull request #1370
Opened 2021-07-21 03:11 UTC by MrMorie

### Fixes [DPC-1438](https://jira.cms.gov/browse/DPC-1438)

### Proposed Changes
DPC's v2 API service does not currently require authentication. We need to use mutual TLS to make that happen.

This PR ads Mutual TLS (MTLS) to DPC-API administrative tasks

### Change Details
- Added mutual to GO DPC API
- Server verifies client certificate
- Server validates clients SAN
- Certificates and Keys are passed in as environmental variables and written to a local file when service starts up.

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] no PHI/PII is affected by this change

### Acceptance Validation

<img width="833" alt="Screen Shot 2021-07-20 at 7 58 06 PM" src="https://user-images.githubusercontent.com/43150956/126424749-d4c3d385-4735-4fce-a97d-a9e1311c7f7e.png">
<img width="976" alt="Screen Shot 2021-07-20 at 8 00 02 PM" src="https://user-images.githubusercontent.com/43150956/126424754-7e7d7e3c-d901-4486-b3a2-f8e852243a72.png">
<img width="354" alt="Screen Shot 2021-07-20 at 7 59 21 PM" src="https://user-images.githubusercontent.com/43150956/126424756-04caff88-16e5-493c-9fdb-4d4c848174fe.png">

### Feedback Requested

2021-08-04 20:55 UTC, MrBilnon approved these changes

2021-08-06 01:51 UTC, MrBilnon approved these changes

2021-08-06 05:13 UTC, MrBilnon submitted a review, later dismissed

2021-08-22 16:37 UTC, orenfromberg requested changes
This branch will validate that a client certificate is signed by the root CA but I think it can be simplified a bit since the functionality that should be verifying client info does not seem to be used.

Instead of signing the portal client cert with the root CA, could we sign with the API cert and key? 
I think that will validate that the portal is the only client of the API. 

Similarly, could we sign the API client cert with the Attribution cert and key? That should also validate that the API is the only client of the Attribution service. 

Doing this may simplify the TLS config for the API server (as well as for the Attribution service), as well as validate that only the clients we expect are talking to the servers.

If we go the route of validating clients are using certs that are signed by the services they are using then would there be any benefit to checking that the client cert has a DNS name in the SAN of the server certificate?

2021-08-22 16:37 UTC, orenfromberg commented on dpc-go/dpc-api/src/service/server.go
> +func getClientValidator(helloInfo *tls.ClientHelloInfo, cerPool *x509.CertPool) func([][]byte, [][]*x509.Certificate) error {
This function doesn't seem necessary because the closure that it returns only checks the DNS names in the SAN field of the server certificate and not any of the client certificate information.

Even if it return a closure that did check the client certificate, it still wouldn't be necessary if the API certificate was used to sign the portals client key and cert because the handshake would only succeed in that situation.

2021-08-22 16:37 UTC, orenfromberg commented on dpc-go/shared/make-certs.sh
> +openssl x509  -req -in local.portal.csr -CA local.ca.crt -CAkey local.ca.key -out local.portal.crt -days 365 -sha256 -CAcreateserial -extfile <(printf "subjectAltName=DNS:localhost,DNS:local.portal.d
if we want to ensure that the only the portal can be a client to the API then should we use the API certificate and key here (`local.api.crt` and `local.api.key`) to sign the portals certificate?

2021-08-22 16:37 UTC, orenfromberg commented on dpc-go/shared/make-certs.sh
> +openssl x509  -req -in local.api.csr -CA local.ca.crt -CAkey local.ca.key -out local.api.crt -days 365 -sha256 -CAcreateserial  -extfile <(printf "subjectAltName=DNS:localhost,DNS:local.api.dpc.cms.g
if we want to ensure that the only the API can be a client to the attribution service then should we use the attribution certificate and key here (`local.attribution.crt` and `local.attribution.key`) to sign the API certificate?

2021-08-22 16:37 UTC, orenfromberg commented on dpc-go/dpc-api/src/service/server.go
> +	s.server.TLSConfig = &tls.Config{
If we relied on the certificate hierarchy to validate the client to the server then would it simplify the TLS config to look like this?
```golang
s.server.TLSConfig = &tls.Config{
  Certificates: []tls.Certificate{cert},
  minVersion: tls.VersionTLS12,
  ClientAuth: tls.RequireAndVerifyClientCert,
  ClientCAs: caPool
}
```

2021-08-22 17:20 UTC, MrMorie commented on dpc-go/dpc-api/src/service/server.go
> +func getClientValidator(helloInfo *tls.ClientHelloInfo, cerPool *x509.CertPool) func([][]byte, [][]*x509.Certificate) error {
The closure checks the client certificate. The server certificate does not contain any of the allowed DNS names, only the client certificates.

It was tested by making a call using the two different client certificates, where only one succeeded and the other failed due to missing DNS entries in the SAN.

But yes, if we go with the your suggested approach of signing the certs with the corresponding server certificate then this verification would not be needed.

2021-08-24 01:48 UTC, orenfromberg commented on dpc-go/dpc-api/src/service/server.go
> +func getClientValidator(helloInfo *tls.ClientHelloInfo, cerPool *x509.CertPool) func([][]byte, [][]*x509.Certificate) error {
I misread that function, thanks for explaining that!

2021-08-24 19:32 UTC, dhgreene commented on dpc-go/shared/make-certs.sh
> +openssl x509  -req -in local.portal.csr -CA local.ca.crt -CAkey local.ca.key -out local.portal.crt -days 365 -sha256 -CAcreateserial -extfile <(printf "subjectAltName=DNS:localhost,DNS:local.portal.d
How does this affect our [key rotation scenarios](https://jira.cms.gov/browse/DPC-1690)?

2021-08-25 05:57 UTC, MrMorie commented on dpc-go/dpc-api/src/service/server.go
> +	s.server.TLSConfig = &tls.Config{
Yep 👍

2021-08-25 14:20 UTC, dhgreene commented on dpc-go/shared/make-certs.sh
> +#Generate CA
Can we please put a comment near the top of this file that it is only for the purpose of generating local certificates?

2021-08-30 15:17 UTC, jonfulk commented
I don't recall closing this... must've been a misclick.

2021-12-01 14:12 UTC, MrMorie commented on dpc-go/shared/make-certs.sh
> +openssl x509  -req -in local.api.csr -CA local.ca.crt -CAkey local.ca.key -out local.api.crt -days 365 -sha256 -CAcreateserial  -extfile <(printf "subjectAltName=DNS:localhost,DNS:local.api.dpc.cms.g
Resolved

2021-12-07 15:59 UTC, orenfromberg commented on dpc-go/dpc-api/src/service/server.go
> +	severTlsConf := &tls.Config{
is that a spelling error?

2021-12-07 16:45 UTC, orenfromberg approved these changes

2021-12-07 16:55 UTC, merged