DPC-1443 Added Mutual TLS between attribution and api (GO)
CMSgov/dpc-app pull request #1373
Opened 2021-07-22 17:21 UTC by MrMorie

### Fixes [DPC-1443](https://jira.cms.gov/browse/DPC-1443)

### Proposed Changes

Currently the connection between DPC-API (GO) and DPC-Attribution (GO) is not secure. This PR secures that connection using MTLS (Mutual TLS)

- Connection should be secured using MTLS
- Server should not just validate client certificate, it should also verify the SAN
- Certificates should be passed in as env variables

### Change Details
- Added MTL to attribution server and API's attribution client.
- Added client SAN check (server side)
- Added logic for parsing certificates passed in via ENV variables.
- Added flag to disable MTLS for local testing purposes. (Enabled by default)

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [X] no PHI/PII is affected by this change

### Acceptance Validation

### Feedback Requested

I was able to test this locally and manually, are we ok with that type of testing until we get integration tests?

Security and certificate implementation
Are we ok with the way certificate parsing is done?

2021-07-22 17:33 UTC, MrMorie commented on dpc-go/dpc-api/src/main.go
> +
the certificate parses did not like the keys without new lines, and I was not able to pass in (non escaped) new lines as an env variable, so this is what I came up with. Any thoughts?

2021-07-22 19:44 UTC, msnook commented on dpc-go/dpc-api/src/main.go
> +
> the certificate parses did not like the keys without new lines, and I was not able to pass in (non escaped) new lines as an env variable, so this is what I came up with. Any thoughts?

@orenfromberg Was this an issue with the effort you did in `bcda-ssas-app`?  Does [this casting ](https://github.com/CMSgov/bcda-ssas-app/pull/84/files#diff-976bf0364f42cfc105090e325b5cea6842e6d61c8692f8106de6ec5ff371784cR54)help?

2021-07-22 19:45 UTC, msnook commented on dpc-go/dpc-attribution/src/main.go
> +		logger.WithContext(ctx).Fatal("Missing server ca cert, env variable CA_CERT is required")
How is this started up/tested locally?  Should a set of test certs be persisted, that are only valid for local environment bootstrapping?

2021-07-22 19:47 UTC, msnook commented on dpc-go/dpc-attribution/src/main.go
> +	caStr := strings.ReplaceAll(conf.GetAsString("CA_CERT"), "\\n", "\n")
For rollout to our AWS envs, will these vars need to be added to the task definition?  Will they need to be manually generated and added to SSM?
What is the plan for getting these certs added to the load balancer and referenced in TF config?
CC: @orenfromberg

2021-07-22 20:33 UTC, dhgreene commented on dpc-go/dpc-api/src/main.go
> +
@MrMorie that can work, we could base64 encode/decode, or I believe there is a way to get the unescaped newlines into an env var.

2021-07-22 20:59 UTC, dhgreene commented on dpc-go/dpc-attribution/src/main.go
> +	caStr := strings.ReplaceAll(conf.GetAsString("CA_CERT"), "\\n", "\n")
> For rollout to our AWS envs, will these vars need to be added to the task definition?

Yes

> Will they need to be manually generated and added to SSM?

That's acceptable. Ideally (maybe eventually?) I'd like them to be managed by the AWS cert manager.

> What is the plan for getting these certs added to the load balancer and referenced in TF config?

Yes, @orenfromberg please help. 🙏

2021-07-22 21:20 UTC, msnook commented on dpc-go/dpc-attribution/src/main.go
> +	caStr := strings.ReplaceAll(conf.GetAsString("CA_CERT"), "\\n", "\n")
> > For rollout to our AWS envs, will these vars need to be added to the task definition?
> 
> Yes
> 
> > Will they need to be manually generated and added to SSM?
> 
> That's acceptable. Ideally (maybe eventually?) I'd like them to be managed by the AWS cert manager.
> 
> > What is the plan for getting these certs added to the load balancer and referenced in TF config?
> 
> Yes, @orenfromberg please help. 🙏

@dhgreene Yes, the cert itself will live in AWS Cert Manager and be referenced (by ARN) in the terraform code for attachment to the internal load balancer.  However, the env vars referenced in this application code will need to pull the specific pieces (public, private, ca, etc) from SSM.

2021-07-23 14:24 UTC, MrMorie commented on dpc-go/dpc-attribution/src/main.go
> +		logger.WithContext(ctx).Fatal("Missing server ca cert, env variable CA_CERT is required")
There is currently a flag that lets you start it up locally without MTLS, I thought about committing certificates but I wasn't sure if that is something we wanted to do.

2021-07-23 14:26 UTC, msnook commented on dpc-go/dpc-attribution/src/main.go
> +		logger.WithContext(ctx).Fatal("Missing server ca cert, env variable CA_CERT is required")
In my opinion, the default should be MTLS and the certs should be persisted.  I can't remember if we use vault for this in the BCDA SSAS env... you might consider taking a look at that pattern for consistency.

2021-07-27 23:28 UTC, dhgreene commented on dpc-go/dpc-api/src/main.go
> +
Let's go with this; if we can get the unescaped newlines into an env var, this code shouldn't break.

2021-08-05 04:32 UTC, dhgreene submitted a review, later dismissed
Let's please talk about our deployment strategy.

2021-08-06 01:52 UTC, MrBilnon approved these changes

2021-08-22 16:48 UTC, orenfromberg requested changes
I think the comments I made in #1370 also apply to this PR. I don't think the client validation is happening the way we expect. I also think the TLS config can be simplified a bit by signing the API client cert with the Attribution cert and key. Would love to know if I am missing something!

2021-11-30 16:38 UTC, dhgreene approved these changes
In conjunction with the recent ops change that configures this to be "off," this is good to go. 👍

2021-11-30 23:06 UTC, orenfromberg approved these changes

2021-12-01 14:10 UTC, merged