Lg 1303 fix
CMSgov/dpc-app pull request #1678
Opened 2022-07-22 14:32 UTC by lgarceau768

## [DPC-1303](https://jira.cms.gov/browse/DPC-1303)

## Change Details
Added the delete public key workflow into the dpc web portal, in the frontend and within the ruby on rails mvc architecture. 
* 

## Security Implications
Should be no security implications no new data is being stored, the accessibility to delete the public key via the portal is the only thing added.

2022-08-03 15:42 UTC, mftcodes commented on dpc-web/app/services/api_client.rb
> +# rubocop:disable Metrics/ClassLength
What's this all about? We're disabling method/class lengths? Then enabling it at the end? If there is a limit set, is it there for a reason and we should stay within it, or is the limit set too low? 
This is all new to me, so take this with a grain of salt.

2022-08-03 15:57 UTC, TiannaW24 commented on dpc-web/app/controllers/public_keys_controller.rb
> +  def destroy
These changes need unit tests.

2022-08-03 15:59 UTC, TiannaW24 commented on dpc-web/app/services/public_key_manager.rb
> +  def delete_public_key(params)
Test?

2022-08-03 16:00 UTC, TiannaW24 commented on dpc-web/app/services/api_client.rb
> +  def delete_public_key(reg_org_api_id, public_key_id)
Tests?

2022-08-03 16:03 UTC, TiannaW24 requested changes
See comments regarding tests. Pretty much every touch to a .rb file should have corresponding unit tests in the _spec.rb file.

2022-08-08 16:19 UTC, TiannaW24 commented on dpc-web/.rubocop.yml
> +Metrics/ClassLength:
Much preferred to disabling/re-enabling 👍🏾

2022-08-08 16:50 UTC, TiannaW24 requested changes

2022-08-08 16:50 UTC, TiannaW24 commented on dpc-web/spec/services/public_key_manager_spec.rb
> +          allow(api_client).to receive(:delete_public_key)
You should have a whole new test suite here that tests the delete functionality the same way this create test suite tests the create functionality.

2022-08-08 16:50 UTC, TiannaW24 commented on dpc-web/spec/controllers/public_keys_controller_spec.rb
> +          expect(response).to render_template(:new)
Are we expecting the correct thing here? Shouldn't a failed call render an error?

2022-08-08 17:16 UTC, lgarceau768 commented on dpc-web/spec/controllers/public_keys_controller_spec.rb
> +          expect(response).to render_template(:new)
I pulled the test suite functionality from the `client_tokens_controller_spec.rb` also I am pretty sure that is correct because the only difference from the main `:new` page when there is an error its rendered as a flash message but still under the `:new` template. (See https://github.com/CMSgov/dpc-app/blob/master/dpc-web/app/controllers/public_keys_controller.rb line 49 and down)

2022-08-09 13:33 UTC, lgarceau768 commented on dpc-web/app/services/api_client.rb
> +# rubocop:disable Metrics/ClassLength
Yes the comment is no longer in the PR

2022-08-09 15:01 UTC, mftcodes submitted a review, later dismissed
These new changes all look good to me!

2022-08-09 15:38 UTC, TiannaW24 commented on dpc-web/spec/services/public_key_manager_spec.rb
> +          allow(api_client).to receive(:delete_public_key)
👍🏾

2022-08-09 16:31 UTC, TiannaW24 approved these changes
Looks great

2022-08-09 17:53 UTC, mftcodes approved these changes
approved

2022-08-09 18:18 UTC, merged