Added USA Banner
CMSgov/dpc-app pull request #1687
Opened 2022-08-23 17:59 UTC by lgarceau768

## [DPC-2761](https://jira.cms.gov/browse/DPC-2716)

## Change Details
Added in USA Banner into the DPC Portal
- added in the `dpc-web`
- added in the `dpc-admin`

No new dependencies or security implications. This is pretty much a direct copy and paste from the [BCDA PR](https://github.com/CMSgov/bcda-static-site/pull/152)

2022-08-23 19:07 UTC, mftcodes approved these changes

2022-08-25 16:46 UTC, TiannaW24 requested changes
This is on hold until I can find out if this is needed for the web-apps

2022-08-31 14:15 UTC, TiannaW24 requested changes
A couple of small changes regarding nav + code placement

2022-08-31 14:15 UTC, TiannaW24 commented on dpc-web/app/views/shared/_navbar.html.erb
> +<section class="ds-c-usa-banner" aria-label="Official government website">
Can we move this code to its own module? Similar to what you did here: https://github.com/CMSgov/dpc-static-site/pull/72/files

2022-08-31 14:15 UTC, TiannaW24 commented on dpc-web/app/views/shared/_navbar.html.erb
> +<section class="ds-c-usa-banner" aria-label="Official government website">
This code is also in the wrong spot. The USA Banner should be above the entire nav. 
<img width="1404" alt="Screen Shot 2022-08-31 at 10 14 28 AM" src="https://user-images.githubusercontent.com/25647797/187700334-24e4de95-009c-43bf-bb0e-0ab908acad85.png">

2022-08-31 14:21 UTC, TiannaW24 commented on dpc-admin/app/views/shared/_navbar.html.erb
> +<section class="ds-c-usa-banner" aria-label="Official government website">
We don't need to add the banner to the admin app, since it's not customer-facing.

2022-08-31 17:55 UTC, TiannaW24 approved these changes
Looks good!

2022-09-06 14:08 UTC, merged