Lg 1473 Pagination of Organizations
CMSgov/dpc-app pull request #1690
Opened 2022-08-30 16:24 UTC by lgarceau768

## [DPC-1473](https://jira.cms.gov/browse/DPC-1473)

## Change Details
Adding pagination to the `client_tokens` and `public_keys` to display a max of 10 records per page.
Using url parameters on the `localhost:3900/?` request, in order to accomplish this (`token_page and key_page`)
Added a new ruby gem [kaminari](https://github.com/kaminari/kaminari)
Used the template generator from kaminari to apply the pagination functionality to the [uswds pagination component](https://designsystem.digital.gov/components/pagination/)
* 

## Security Implications
Does not connect to the database calls at all. Only manipulating the array of client tokens and public keys after it has already been retrieved (purely ruby on rails logic)
- [x] new software dependencies
No major issues within the dependency [(found here)](https://codeclimate.com/github/kaminari/kaminari/issues?severity%5B%5D=major&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed)

## Todo
This was not a part of the AC but I think it find value in doing, currently the user is able to put in any number into the url parameters and render the records for client tokens or public keys that would be on that page. 

example:
I user have 15 client tokens and 10 public keys, therefore by [DPC-1473](https://jira.cms.gov/browse/DPC-1473) AC there will be 3 pages of client tokens and 2 pages of public keys. 
The url for the last page of client tokens would look like this `https://localhost:3900/?token_page=3`
The user can input this incorrect url `https://localhost:3900/?token_page=4` and not get a 404 request and just will see an empty table. (I think this should pop up a flash message and default to the last page, still need to add this functionality, but also think that it has crossed to being worth it to add to the dpc-app even without this functionality)

2022-08-30 20:09 UTC, mftcodes requested changes
Other than the white space, this looks good to me.

2022-08-30 20:09 UTC, mftcodes commented on dpc-web/app/views/portal/_assigned_content.html.erb
> +              </tbody>
Remove Whitespace

2022-08-30 20:09 UTC, mftcodes commented on dpc-web/app/views/portal/_assigned_content.html.erb
> +              </tbody>
Remove whitespace

2022-08-31 14:08 UTC, TiannaW24 requested changes
Functionality looks good. Can we add one thing: we need an indicator showing which page the user is currently on.

2022-08-31 18:22 UTC, mftcodes commented on dpc-web/app/assets/stylesheets/utilities/_add-ons.scss
> +  color: white !important;
Anyway to increase specificity here rather than using `!important`?

2022-08-31 19:05 UTC, TiannaW24 approved these changes

2022-08-31 19:05 UTC, TiannaW24 commented on dpc-web/app/assets/stylesheets/utilities/_add-ons.scss
> +  color: white !important;
+1 to this

2022-09-06 13:00 UTC, mftcodes approved these changes

2022-09-06 16:22 UTC, merged