Snyk Critical / High Dependency Updates
CMSgov/dpc-app pull request #1701
Opened 2022-09-20 20:23 UTC by lgarceau768

## [DPC-2811](https://jira.cms.gov/browse/DPC-2811)
**(dependencies only)**
## Change Details
- updated to rails 6.1.4.1 to fix the critical vulnerabilities within `activestorage` and `activerecord` version `6.0.5.1`

2022-09-22 17:36 UTC, lgarceau768 commented
https://app.snyk.io/org/oeda/project/70afbed4-f7f9-45ae-8309-f70a09ed2541/history/fcb38939-483c-468d-b179-5dfbc1003ff0
https://app.snyk.io/org/oeda/project/e516d0a4-41f3-47ce-b950-c4694276110a/history/65ea5638-2dcf-4b46-b6c9-a2bd35e4f3c4
https://app.snyk.io/org/oeda/project/08f57c4d-1636-4972-afa7-81908d4a170f/history/f7b6d7bd-ae85-4231-a933-27417d471a07
https://app.snyk.io/org/oeda/project/d8ade90c-9828-4592-916a-bfb4ff9cd6a5/history/10772d2c-c139-457d-bf69-ba6209c5dc77
https://app.snyk.io/org/oeda/project/97e80ab5-8c9b-4106-b345-f347f0fc03ec/history/db900d12-e8a0-4b52-9ddc-a9e03c794857https://app.snyk.io/org/oeda/project/65656540-4a4d-4330-a818-2af9ef39a20f/history/eed1dda7-3a75-4bfe-aa41-8effd12abd72
https://app.snyk.io/org/oeda/project/4fd730b7-5355-4fea-82d6-d6ff845c416c/history/7ca0c14e-144b-48bc-83b3-dddda7c86f95
https://app.snyk.io/org/oeda/project/a3af8216-baad-42ae-9a15-d3ea78721131/history/abfdb298-5907-47b3-b8e3-03d851d776b7
https://app.snyk.io/org/oeda/project/fb1567c5-02c6-4634-87fb-d2d658a2632f/history/db910a2d-8be1-4aec-8a38-7b14f2cdfcd6
https://app.snyk.io/org/oeda/project/ccebd48c-2d45-4526-9f02-e926b18933c6/history/57d1729a-81d2-40ff-94b8-30c2d0783186
https://app.snyk.io/org/oeda/project/ebed4972-3f33-4d7a-b056-5d62489524d8/history/77ef218e-003c-46f2-a1f6-8048c13f84d1
https://app.snyk.io/org/oeda/project/4c8790fb-c3a1-4d71-b713-0b6c0104c9e3/history/bb8455bb-1250-4d4c-9f1f-71f76974a58f
https://app.snyk.io/org/oeda/project/b62e1798-f824-4982-9008-be9882798d24/history/5b1c509a-37a6-4610-a1ee-4567b78ce6a7
https://app.snyk.io/org/oeda/project/30bc0649-fc10-4299-8e7b-18da0a48a5ee/history/062e4af5-3119-417f-b350-73d4c13bcf2c
https://app.snyk.io/org/oeda/project/70f6e2ca-cfcd-4813-9983-2d79b2106d00/history/ec0efe75-7fad-43ed-8d40-2b49119a20fd
https://app.snyk.io/org/oeda/project/60fe9439-5b98-4768-b081-f21e57afbe23/history/584eb0ee-b8c1-4f22-ad9d-e09894094984
https://app.snyk.io/org/oeda/project/67792d99-e301-4ee8-9347-083d3f2c5202/history/4b6aa6c6-38e0-451a-baae-4da635bd985a
https://app.snyk.io/org/oeda/project/07d465b5-bf18-4898-b3f3-ee0c2bae2851/history/9a4a260c-59e1-40db-a2b8-ee647a95edc0
https://app.snyk.io/org/oeda/project/38c520a6-c0db-400d-9120-52d43c46d124/history/5894ee90-d80c-4122-974d-3cb982842c8d

2022-09-23 15:33 UTC, TiannaW24 requested changes
Comments surrounding why new gems were introduced and why some gems went back a minor version

2022-09-23 15:33 UTC, TiannaW24 commented on dpc-admin/Gemfile
> +gem 'rails', '~> 6.1.6.1'
I believe rails was omitted to avoid pulling in actioncable, which is not used. We should continue to follow that pattern.

2022-09-23 15:33 UTC, TiannaW24 commented on dpc-admin/Gemfile
> +gem 'actionmailbox', '>= 6.0.5.1'
I believe this is rolling us back a minor version, which we wouldn't want.

2022-09-23 15:33 UTC, TiannaW24 commented on dpc-adminv2/Gemfile
> +gem 'faraday-retry'
Brand new gem? Why was this added?

2022-09-23 15:37 UTC, TiannaW24 commented on dpc-admin/Gemfile
>  # Specifying rails components to be able to omit unused actioncable
This is the comment stating why we don't pull in rails

2022-09-28 16:59 UTC, closed without merging