Active Snyk Updates
CMSgov/dpc-app pull request #1713
Opened 2022-10-06 14:15 UTC by lgarceau768

active family & action family , railties, and newrelic

## [DPC-2811](https://jira.cms.gov/browse/DPC-2811)

## Change Details

* 

## Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] PHI/PII is affected by this change

2022-10-13 14:54 UTC, TiannaW24 requested changes
Need some explanation as to some of the changes. Actual requested changes surround the changes in the user_spec.rb files. Not sure we're approaching that correctly.

2022-10-13 14:54 UTC, TiannaW24 commented on dpc-admin/spec/models/user_spec.rb
> +      begin
Hmmm I don’t like the switch up in this test. The original test was testing that the User object was invalid if the email had an invalid domain. Now we’re only testing that the validator returns false for a bad domain. But we should be doing the first. I'm wondering if the way we're declaring the `domain_exists: true` validator in the User.rb file is incorrect.

2022-10-13 14:54 UTC, TiannaW24 commented on dpc-admin/config/environments/production.rb
> +  config.assets.js_compressor = Uglifier.new(:harmony => true)
If you're going to change production config files, you're going to need to provide explanations of what your changes are.

2022-10-13 14:54 UTC, TiannaW24 commented on dpc-web/config/initializers/devise.rb
> +  config.mailer = 'Devise::Mailer'
Why the switch up here?

2022-10-13 15:14 UTC, lgarceau768 commented on dpc-web/config/initializers/devise.rb
> +  config.mailer = 'Devise::Mailer'
Because with the update of the depedency there was an issue with the application recognizing Devise::Mailer.layout  and that is the change we found to be successful. https://github.com/CMSgov/dpc-app/actions/runs/3197885565/jobs/5221700507

2022-10-13 15:35 UTC, TiannaW24 commented on dpc-web/spec/models/user_spec.rb
> +
Can you get rid of these whitespaces.

2022-10-13 15:56 UTC, mftcodes commented on dpc-web/config/initializers/devise.rb
> +  config.mailer = 'Devise::Mailer'
I helped with this area of code, and what I learned through the process was quit simply that the way this was being initialized before was just wrong. This whole file is setting up the devise set-up we're using through the use of the `config` object, and the previous initialization was not assigning the `config.mailer` to anything.
I spent some time reading through some documentation on devise in GitHub (mainly, this helped https://github.com/heartcombo/devise/wiki/How-To:-Use-custom-mailer) and reading through our code, and it just became apparent that we were using the wrong syntax. I then found the commented out line and that's when it all came together.

2022-10-13 16:54 UTC, TiannaW24 commented on dpc-admin/config/environments/production.rb
> +  config.assets.js_compressor = Uglifier.new(:harmony => true)
Got it thanks.

2022-10-13 17:02 UTC, TiannaW24 commented on dpc-adminv2/spec/models/user_spec.rb
> +        r = Truemail.validate(subject.email).result.success
Revert as well

2022-10-13 17:02 UTC, TiannaW24 commented on dpc-impl/spec/models/user_spec.rb
> +      begin
Revert

2022-10-13 18:04 UTC, mftcodes commented on dpc-admin/spec/models/user_spec.rb
> +      rescue StandardError
These cannot be reverted, only refactored. The previous test were failing due to the change in the mailer framework. So, we need to define what we want to test and re-write. I'd propose we either do that now and extend this ticket, or let this through this PR and create a new ticket for better test coverage.

2022-10-13 19:28 UTC, TiannaW24 commented on dpc-admin/spec/models/user_spec.rb
> +      rescue StandardError
Not sure what you mean. The testing condition for this unit test was initially correct. We want to make sure the User object is invalid if the email domain is invalid. These changes do not test for that, they test for whether the email validator returns true or false. Take a look at the changes Luke made in the domain_exists_validator.rb file. If that works and does add an error on the model for an invalid email domain, then we should be able to revert this test and have it pass.

2022-10-13 19:44 UTC, lgarceau768 commented on dpc-admin/spec/models/user_spec.rb
> +      rescue StandardError
Fixed in the latest commit

2022-10-14 11:59 UTC, TiannaW24 commented on dpc-web/spec/models/user_spec.rb
> +
@lgarceau768 still there...

2022-10-14 12:59 UTC, TiannaW24 commented on dpc-adminv2/app/validators/domain_exists_validator.rb
> +end
rubocop is complaining about the missing newline here

2022-10-14 13:00 UTC, TiannaW24 commented on dpc-impl/app/validators/domain_exists_validator.rb
> +end
Newline

2022-10-14 13:00 UTC, TiannaW24 commented on dpc-web/app/validators/domain_exists_validator.rb
> +end
Newline needed

2022-10-14 15:59 UTC, TiannaW24 commented on dpc-web/config/initializers/devise.rb
> -  Devise::Mailer.layout "mailer"
Why did we remove this line?

2022-10-14 15:59 UTC, TiannaW24 commented on dpc-web/config/initializers/devise.rb
> +  config.mailer = 'Devise::Mailer'
Got it 👍🏾

2022-10-14 16:10 UTC, lgarceau768 commented on dpc-web/config/initializers/devise.rb
> +  config.mailer = 'Devise::Mailer'
https://github.com/CMSgov/dpc-app/blob/d6157b7de811e06c28600bda8695b75a23d891a9/dpc-web/config/application.rb#L63
The default view for the mailer is defined here

2022-10-14 16:10 UTC, lgarceau768 commented on dpc-web/config/initializers/devise.rb
> -  Devise::Mailer.layout "mailer"
https://github.com/CMSgov/dpc-app/blob/d6157b7de811e06c28600bda8695b75a23d891a9/dpc-web/config/application.rb#L63

2022-10-14 16:18 UTC, TiannaW24 commented on dpc-web/config/initializers/devise.rb
> -  Devise::Mailer.layout "mailer"
👍🏾

2022-10-14 16:18 UTC, TiannaW24 approved these changes

2022-10-14 16:25 UTC, merged