Lgarceau/dpc2922
CMSgov/dpc-app pull request #1744
Opened 2022-11-22 17:56 UTC by lgarceau768

## [DPC-xxxx](https://jira.cms.gov/browse/DPC-xxxx)

## Change Details

* 

## Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] PHI/PII is affected by this change

2022-11-30 17:17 UTC, lgarceau768 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +        final UUID jobID = UUID.randomUUID();
Had to assign a UUID to the created `Patient/$everything` requests because they were not being logged with the information needed otherwise.

2022-11-30 17:17 UTC, lgarceau768 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +        final String eventTime = Instant.now().toString().replace("T", " ").substring(0, 22);
This format was for ease of interpretation within Splunk.

2022-11-30 17:17 UTC, lgarceau768 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java
> +        final String eventTime = Instant.now().toString().replace("T", " ").substring(0, 22);
This format was for ease of interpretation within Splunk.

2022-11-30 17:17 UTC, lgarceau768 commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java
> +                final String jobTime = Instant.now().toString().replace("T", " ").substring(0, 22);
This format was for ease of interpretation within Splunk.

2022-11-30 17:17 UTC, lgarceau768 commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java
> +        final String queueCompleteTime = Instant.now().toString().replace("T", " ").substring(0, 22);
This format was for ease of interpretation within Splunk.

2022-11-30 17:33 UTC, lgarceau768 commented
Query for 99th Percentile Calculation of Queue Duration
```
| table jobID
| appendcols [ search dpcMetric="queueSubmitted"]
| appendcols [ search dpcMetric="queueComplete"]
| eval queueSTime=strptime('queueSubmitTime', "%Y-%m-%d %H:%M:%S.%N")
| eval queueCTime=strptime('queueCompleteTime', "%Y-%m-%d %H:%M:%S.%N")
| eval queueDuration=('queueCTime'-'queueSTime')
| sort -queueDuration
| stats perc99(queueDuration) as "99th% Queue Duration (sec)"
```

2022-11-30 17:34 UTC, lgarceau768 commented
Query for 99th Percentile Calculation of Job Duration
```
| table jobID
| appendcols [ search dpcMetric="jobComplete"]
| appendcols [ search dpcMetric="queueComplete"]
| eval queueCTime=strptime('queueCompleteTime', "%Y-%m-%d %H:%M:%S.%N")
| eval jobCTime=strptime('jobCompleteTime', "%Y-%m-%d %H:%M:%S.%N")
| eval requestDuration=('jobCTime'-'queueCTime')
| sort -requestDuration
| stats perc99(requestDuration) as "99th% BFD Request Duration 
```

2022-11-30 17:35 UTC, lgarceau768 commented
Query for 99th Percentile Calculation of Job Duration
```
| table jobID
| appendcols [ search dpcMetric="queueSubmitted"]
| appendcols [ search dpcMetric="jobComplete"]
| eval queueSTime=strptime('queueSubmitTime', "%Y-%m-%d %H:%M:%S.%N")
| eval jobCTime=strptime('jobCompleteTime', "%Y-%m-%d %H:%M:%S.%N")
| eval jobDuration=('jobCTime'-'queueSTime')
| sort -jobDuration
| stats perc99(jobDuration) as "99th% Job Duration (sec)"
```

2022-11-30 17:36 UTC, TiannaW24 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +        final UUID jobID = UUID.randomUUID();
Why is this UUID being created?

2022-11-30 17:37 UTC, lgarceau768 commented
Query for Average BFD Request Calculation
```
| table jobID
| appendcols [ search dpcMetric="jobComplete"]
| appendcols [ search dpcMetric="queueComplete"]
| eval queueCTime=strptime('queueCompleteTime', "%Y-%m-%d %H:%M:%S.%N")
| eval jobCTime=strptime('jobCompleteTime', "%Y-%m-%d %H:%M:%S.%N")
| eval requestDuration=('jobCTime'-'queueCTime')
| sort -requestDuration
| stats avg(requestDuration) as "Average BFD Request Duration (sec)"
```

2022-11-30 17:38 UTC, lgarceau768 commented
Query for Average Calculation of Total Job Duration 
```
| table jobID
| appendcols [ search dpcMetric="queueSubmitted"]
| appendcols [ search dpcMetric="jobComplete"]
| eval queueSTime=strptime('queueSubmitTime', "%Y-%m-%d %H:%M:%S.%N")
| eval jobCTime=strptime('jobCompleteTime', "%Y-%m-%d %H:%M:%S.%N")
| eval jobDuration=('jobCTime'-'queueSTime')
| sort -jobDuration
| stats avg(jobDuration) as "Average Job Duration (sec)"
```

2022-11-30 17:48 UTC, TiannaW24 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +        final UUID jobID = UUID.randomUUID();
The dataService.retrieveData method creates a JobID for the request: [dpc-app/dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java](https://github.com/CMSgov/dpc-app/blob/master/dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java#L74)

Can we leverage that?

2022-11-30 17:50 UTC, lgarceau768 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +        final UUID jobID = UUID.randomUUID();
Let me look into it!

2022-11-30 17:52 UTC, TiannaW24 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/GroupResource.java
> +        logger.info("dpcMetric=queueSubmitted,requestUrl={},jobID={},orgId={},totalPatients={},resourcesRequested={},queueSubmitTime={}", "/Group/$export",jobID, orgID, totalPatients, resourcesReques
I think this is the only place I see where we're logging "Group/$export". Should the equivalent for Patient/$everything be somewhere in here too?

2022-11-30 18:00 UTC, lgarceau768 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +        final UUID jobID = UUID.randomUUID();
It has been addressed in the latest push!

2022-11-30 18:04 UTC, mftcodes requested changes
Looks good to me, except my suggestion to put the time formatting in a reusable function some where.

2022-11-30 18:04 UTC, mftcodes commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java
> +        final String queueCompleteTime = Instant.now().toString().replace("T", " ").substring(0, 22);
You're repeating this code a lot. Is there a place we can put this to make it reusable? If we ever need to make an adjustment that would save us a lot of time and effort if it was just one place. Do we have any helper type libraries/files we could put this into?

2022-11-30 18:04 UTC, mftcodes commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +
whitespace, let's remove this, please.

2022-11-30 18:04 UTC, mftcodes commented on dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java
> +        final String eventTime = Instant.now().toString().replace("T", " ").substring(0, 22);
again, let's put this in a function somewhere... We have it twice within 10 lines.

2022-11-30 18:04 UTC, TiannaW24 commented on dpc-api/src/main/java/gov/cms/dpc/api/resources/v1/PatientResource.java
> +
Is this Github being weird again?

2022-11-30 18:07 UTC, TiannaW24 commented on dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java
> +            LOGGER.info("dpcMetric=jobComplete,completionResult={},jobID={},jobCompleteTime={}", "COMPLETE", jobID, jobTime);
Can we move these lines inside the successful if condition below?

2022-12-01 20:06 UTC, mftcodes approved these changes
we need a real 👨🏻‍🍳 💋 emoticon for this type of thing...

2022-12-02 14:53 UTC, TiannaW24 commented on dpc-api/src/main/java/gov/cms/dpc/api/APIHelpers.java
> +    public static String getSplunkTimestamp() {
Yes to this!

2022-12-02 14:57 UTC, TiannaW24 commented on dpc-api/src/main/java/gov/cms/dpc/api/APIHelpers.java
> +    public static String getSplunkTimestamp() {
OK, so I see where you were going with this, trying to reduce code duplication, but really all we did was duplicate it in a bunch of different places. Consider utilizing the dpc-common package for shared utils across the services. Classes from the common library can be imported into any of the other services, aggregation, queue, api, etc. Example: https://github.com/CMSgov/dpc-app/blob/master/dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/AggregationEngine.java#L5

2022-12-02 15:07 UTC, TiannaW24 commented on dpc-queue/src/main/java/gov/cms/dpc/queue/service/DataService.java
> +                LOGGER.info("dpcMetric=jobError,completionResult={},jobID={},jobCompleteTime={}", "FAILED", jobID, jobTime);
Sorry, I think my comment on this wasn't clear. We should have this logging here AND on line 100 but I want to use a different completionResult for the log on line 100. FAILED can be for normal (expected) failures but on line 100 we should use some kind of completionResult that signifies something went REALLY wrong. The only thing I can think to use is ERROR or APPLICATIONERROR. Any ideas?

2022-12-02 15:53 UTC, mftcodes commented on dpc-common/src/main/java/gov/cms/dpc/common/logging/SplunkTimestamp.java
> +        return Instant.now().toString().replace("T", " ").substring(0, 22);
There we go! Yes, even better! 👨🏻‍🍳 💋

2022-12-02 16:28 UTC, TiannaW24 approved these changes

2022-12-02 16:43 UTC, TiannaW24 commented on .github/workflows/ci-workflow.yml
> +    runs-on: ubuntu-20.04
Latest version of ubuntu installation has a bug when installing Python 2 or 3. Pinning this version after guidance from: https://github.com/actions/setup-python/issues/162

2022-12-02 16:52 UTC, TiannaW24 approved these changes

2022-12-02 19:53 UTC, merged

2022-12-13 19:35 UTC, lgarceau768 commented
Had to update the queries to include the line 
`AND NOT mdc.is_smoke_test="true"`
to the line below to remove smoke test requests from the data collection
`| append [ search dpcMetric="XYZ"]`
The line is now as follows below (everywhere it is used within a query)
`| append [ search dpcMetric="XYZ" AND NOT mdc.is_smoke_test="true"`