Jnasim/dpc 2815
CMSgov/dpc-app pull request #1783
Opened 2022-12-22 20:31 UTC by knasim

## [DPC-xxxx](https://jira.cms.gov/browse/DPC-xxxx)

## Change Details

* 

## Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] PHI/PII is affected by this change

2022-12-23 19:44 UTC, mftcodes requested changes
Check comments. I think one comment we can remove, and the others I wonder if they were left for yourself as a reminder or testing?

2022-12-23 19:44 UTC, mftcodes commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java
> +        //return fetcher.fetchResources(patientID, buildHeaders(job))
Can we remove this comment please?

2022-12-23 19:44 UTC, mftcodes commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobHeaders.java
> +            headers.put(Constants.BlueButton.ORIGINAL_QUERY_TIME_STAMP_HEADER,job.getTransactionTime().toString()); //test this
Do we need the `//test this` comments on these lines?

2022-12-23 19:44 UTC, mftcodes commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobHeaders.java
> +}
I like the use of class here!

2022-12-27 14:49 UTC, lgarceau768 requested changes
Some minute changes

2022-12-27 14:49 UTC, lgarceau768 commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java
> +        //return fetcher.fetchResources(patientID, buildHeaders(job))
I second this change

2022-12-27 14:49 UTC, lgarceau768 commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobHeaders.java
> +            headers.put(Constants.BlueButton.ORIGINAL_QUERY_TIME_STAMP_HEADER,job.getTransactionTime().toString()); //test this
Yes please remove the `//test this`

2022-12-27 18:13 UTC, knasim commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobBatchProcessor.java
> +        //return fetcher.fetchResources(patientID, buildHeaders(job))
removed.

2022-12-27 18:13 UTC, knasim commented on dpc-aggregation/src/main/java/gov/cms/dpc/aggregation/engine/JobHeaders.java
> +            headers.put(Constants.BlueButton.ORIGINAL_QUERY_TIME_STAMP_HEADER,job.getTransactionTime().toString()); //test this
they are removed now - added those as reminders to myself.

2022-12-28 14:44 UTC, lgarceau768 approved these changes

2022-12-28 16:30 UTC, merged

2022-12-28 16:39 UTC, knasim commented
Dismissed review in order to allow secondary reviewer to complete the merge.  Primary reviewer is OOO till next year and this blocks secondary reviewer from merging.