Remove offending test
CMSgov/dpc-app pull request #1804
Opened 2023-01-20 22:51 UTC by mftcodes

## [DPC-3163](https://jira.cms.gov/browse/DPC-3163)

## Change Details

* Removing a test in a golang file that exposed the unencrypted bfdHashPepper for PROD_SBX

## Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] PHI/PII is affected by this change

2023-01-20 23:26 UTC, famegashie submitted a review, later dismissed
Reviewed.

2023-01-23 15:25 UTC, lgarceau768 requested changes
I think the version upgrades should be moved to a new PR but my mind can be changed!

2023-01-23 18:37 UTC, mftcodes commented on dpc-web/Gemfile
>  # Anchored versions, do not bump without testing
I can separate a PR to upgrade all of these, and a PR to remove the test. All the upgraded packages are necessary to even get a build to finish. Is this the separate you mean?

2023-01-23 18:59 UTC, lgarceau768 approved these changes
Reviewed and looks good!

2023-01-23 19:35 UTC, merged